### ISSUE TITLE
ValueError Issue with more than 2 clf!!!

### ISSUE THREAD

**Issue by HRezaeiM** [younggns/comparative-abusive-lang#2]
I have been trying to run your code ! which is giving me lots of error and when I fix one another one pops up! 
the issue here is that there is `ValueError: could not convert string to float: 'macro' ` which is basically happening for CNN and SVM as well! so the problem is with both wrappers that you have provided here.

> Traceback (most recent call last):
  File "wrapper_nn.py", line 299, in <module>
    models_cnn.test_word_cnn(use_glove, use_ctxt, 10)
  File "/home/hoora/Documents/Training/comparative-abusive-lang/model/models_cnn.py", line 311, in test_word_cnn
    tot_report = report_average(report_list)
  File "/home/hoora/Documents/Training/comparative-abusive-lang/model/models_cnn.py", line 54, in report_average

here is the error when I have tried to run CNN with these configs : 
Hybrid CNN? (True/False):     False
Use context tweet? (True/False): True 

#############################
#############################

Batch size:                   1003
Number of epoch:              100
Filter sizes (e.g. 1,2,3):    3
Number of filters:            3
Train embedding? (True/False): False
Learning rate:                0.3

after epoch 6th didn't improve it gave this error! 

Also for the SVM, I have tried with this config : 

ngram range (n1,n2):     1,5
max number of features:  10

> Done training.
Evaluating the test results...
Traceback (most recent call last):
  File "wrapper_ml.py", line 142, in <module>
    evaluate(args["feature_level"], args["clf"])
  File "wrapper_ml.py", line 125, in evaluate
    tot_report = report_average(report_list)
  File "wrapper_ml.py", line 100, in report_average
    avg_total = np.array([x for x in splitted[2].split(' ')][3:]).astype(float).reshape(-1, len(header))
ValueError: could not convert string to float: 'macro'

For test on RNN with this config : 

Using TensorFlow backend.
Process vocab? (True/False):  True
Use GloVe? (True/False):      False

<pre>Bunch of lines like this : 
Saved in /home/Jane/Documents/Training/comparative-abusive-lang/model/../data/preprocessed/word/0/train_CtxtText_InputText.npy. (55117, 200)
</pre>

one creating vocabulary pickles
Vocabulary loaded with 66314 words
Generating random embedding.

#############################
#############################

Batch size:                   100
Encoder size:                 100
Number of layers:             2 
Hidden layer dimension:       3
Number of train steps:        100
Learning rate:                0.2
Dropout probability:          0.5
Save best result? (True/False):True
Apply attention? (True/False):True
Apply LTC? (True/False):      False
Graph prefix:                 Test

> Traceback (most recent call last):
  File "wrapper_nn.py", line 310, in <module>
    os.system("python3 models_rnn.py --batch_size "+batch_size+" --encoder_size "+encoder_size+" --num_layer "+num_layer+" --hidden_dim "+hidden_dim+" --lr "+lr+" --num_train_steps "+num_train_steps+" --is_save "+is_save_rnn+" --dr "+dr+" --use_glove "+use_glove_rnn+" --attn "+attn_rnn+" --ltc "+ltc_rnn+" --graph_prefix "+graph_prefix+" --data_path "+data_path)
TypeError: must be str, not int

So I am not quite sure how to solve these ! and is the code actually gonna work or not? because if it's not I rather not put more effort into it. 
I would appreciate your help on this issue.

**Comment by david-yoon** [comment]
Hi Hoora,

I just checked the RNN codes (train_rnn, train_rnn_ctx) and found it worked for my case with the preprocessed dataset I have.
Let me share you the preprocessed dataset via an email.

Thank you,
David

**Comment by HRezaeiM** [comment]
> Hi Hoora,
> 
> I just checked the RNN codes (train_rnn, train_rnn_ctx) and found it worked for my case with the preprocessed dataset I have.
> Let me share you the preprocessed dataset via an email.
> 
> Thank you,
> David

Is there anything specific for your dataset? As I have run the code with exact steps as it was mentioned I found this error. I was wondering shouldn't the code work regardless of the data? :-?

**Comment by david-yoon** [comment]
> Is there anything specific for your dataset? As I have run the code with exact steps as it was mentioned I found this error. I was wondering shouldn't the code work regardless of the data? :-?

The preprocess codes are maintained by the main author. I'm not quite sure the differences between the preprocessed dataset I already have and the one generating by the code in this repository. I'll ask him.

**Comment by younggns** [comment]
Hi, @HRezaeiM Thanks for your interest in our research, and I'm sorry for the inconvenience you had.
It turns out that sklearn library for generating classification report has been changed since our initial code distribution, and hence the issue was caused in 'report_average' function. In this function, we did some slicing to get the weighted average value of F1 score from the string output given by _sklearn.metrics.classification_report_. It seems _classification_report_ now gives more information as a string output, and this was the reason for the error. I have changed the code for 'report_average', and I believe you should be able to get the result. Thanks!

**Comment by Louis-udm** [comment]
Frankly speaking, although this is just a workshop article, the code is really messy, unclear, and a lot of mistakes.

And I hope you could describe the format of the datafile needed for train_rnn.py, which npy files will be read into train_rnn.py, and how is each npy file organized?

**Comment by younggns** [comment]
> Frankly speaking, although this is just a workshop article, the code is really messy, unclear, and a lot of mistakes.
> 
> And I hope you could describe the format of the datafile needed for train_rnn.py, which npy files will be read into train_rnn.py, and how is each npy file organized?

@Louis-udm It is very disrespectful for you to degrade someone else's research work just because you were not able to run the code. We addressed and corrected the errors, and have confirmed that the code works. However, as I mentioned in response to your email, we cannot run the model and do your work for you, nor babysit the preprocessing steps you want to run. Needless to say, you need to be responsible and independent in your own research. If you are capable enough to judge the clearness of the code, I believe you can easily figure out something you want to know—data format, etc.— from our code as well. I am hiding your comment since it is irrelevant to the issue above.

**Comment by Louis-udm** [comment]
> > Frankly speaking, although this is just a workshop article, the code is really messy, unclear, and a lot of mistakes.
> > And I hope you could describe the format of the datafile needed for train_rnn.py, which npy files will be read into train_rnn.py, and how is each npy file organized?
> 
> @Louis-udm It is very disrespectful for you to degrade someone else's research work just because you were not able to run the code. We addressed and corrected the errors, and have confirmed that the code works. However, as I mentioned in response to your email, we cannot run the model and do your work for you, nor babysit the preprocessing steps you want to run. Needless to say, you need to be responsible and independent in your own research. If you are capable enough to judge the clearness of the code, I believe you can easily figure out something you want to know—data format, etc.— from our code as well. I am hiding your comment since it is irrelevant to the issue above.

I am sorry, if you are not willing to listen to sincere suggestions. I accept what you said should get the baseline yourself. But I think it's better to help each other in the field of research and to provide information to those who follow your research, and this is also your value. All we know code is the code, code is not everything.

**Comment by HRezaeiM** [comment]
Honestly, I appreciate all the help that you guys are giving and for your responses but the issue is that the code is still not working! 
I have tried it with the data that @david-yoon uploaded with SVM and I got this error back : 

> Traceback (most recent call last):
  File "wrapper_ml.py", line 141, in <module>
    train(args["feature_level"], ngram_range, int(max_features), args["clf"])
  File "wrapper_ml.py", line 32, in train
    with open(path+"/../data/preprocessed/"+feature_level+"/data_splits.pkl", "rb") as f:


I guess the files are not in the order they should be or something but I also couldn't find any "data_splits.pkl" in the whole preprocessed data that you provided here :(

I have also tried with the RNN ! 
![Screenshot from 2019-07-03 12-00-18](https://user-images.githubusercontent.com/25917418/60739922-4add3f80-9f29-11e9-9c18-d3f8c5932ff7.png) and you can see the error into the screenshot !

**Comment by david-yoon** [comment]
> Honestly, I appreciate all the help that you guys are giving and for your responses but the issue is that the code is still not working!
> I have tried it with the data that @david-yoon uploaded with SVM and I got this error back :
> 
> > Traceback (most recent call last):
> > File "wrapper_ml.py", line 141, in 
> > train(args["feature_level"], ngram_range, int(max_features), args["clf"])
> > File "wrapper_ml.py", line 32, in train
> > with open(path+"/../data/preprocessed/"+feature_level+"/data_splits.pkl", "rb") as f:
> 
> I guess the files are not in the order they should be or something but I also couldn't find any "data_splits.pkl" in the whole preprocessed data that you provided here :(
> 
> I have also tried with the RNN !
> ![Screenshot from 2019-07-03 12-00-18](https://user-images.githubusercontent.com/25917418/60739922-4add3f80-9f29-11e9-9c18-d3f8c5932ff7.png) and you can see the error into the screenshot !

@HRezaeiM
Hi Hoora,
As we've talked via email, the reason I provided the preprocessed dataset is just test purpose of the RNN codes (except character-level RNN).
I did not release the preprocessed dataset for the character-level RNN, so you got the errors in the screenshot.

I also modified the front page to make it clear.
"[for quick test purpose] preprocessed dataset [link] 
(works only for the RNN models (train_rnn.py, train_rnn_ctx.py) except for character-level RNN (train_rnn_char.py) )"

Thank you,
David

**Comment by younggns** [comment]
> data_splits.pkl



> > Honestly, I appreciate all the help that you guys are giving and for your responses but the issue is that the code is still not working!
> > I have tried it with the data that @david-yoon uploaded with SVM and I got this error back :
> > > Traceback (most recent call last):
> > > File "wrapper_ml.py", line 141, in
> > > train(args["feature_level"], ngram_range, int(max_features), args["clf"])
> > > File "wrapper_ml.py", line 32, in train
> > > with open(path+"/../data/preprocessed/"+feature_level+"/data_splits.pkl", "rb") as f:
> > 
> > 
> > I guess the files are not in the order they should be or something but I also couldn't find any "data_splits.pkl" in the whole preprocessed data that you provided here :(
> > I have also tried with the RNN !
> > ![Screenshot from 2019-07-03 12-00-18](https://user-images.githubusercontent.com/25917418/60739922-4add3f80-9f29-11e9-9c18-d3f8c5932ff7.png) and you can see the error into the screenshot !
> 
> @HRezaeiM
> Hi Hoora,
> As we've talked via email, the reason I provided the preprocessed dataset is just test purpose of the RNN codes (except character-level RNN).
> I did not release the preprocessed dataset for the character-level RNN, so you got the errors in the screenshot.
> 
> I also modified the front page to make it clear.
> "[for quick test purpose] preprocessed dataset [link]
> (works only for the RNN models (train_rnn.py, train_rnn_ctx.py) except for character-level RNN (train_rnn_char.py) )"
> 
> Thank you,
> David

@HRezaeiM We have recently updated the code to make the workflow more streamlined. Please refer to the new code if you still have troubles in ML models! For data_splits.pkl file, you will need to run data_preprocess.py file to generate it. Our previous code required to run this script separately for word-level and character-level features, which made the workflow messier. I guess you might run data_preprocess.py script for one feature(let's say it was word feature), but not for another(character feature), and the error occurred. The newly updated code has changed the way of storing the data, and it only requires running data_preprocess.py file once. Hope this would help.

**Comment by HRezaeiM** [comment]
Well, I guess its a lot of time I have put on this code to get it working so I can use it for a part of my code possibly! 
and it still needs more work for me to make a pickle file and go through the whole process all over again !!
I guess I should have given up already and try to write it for myself! 
thanks for trying to get your code running in a less messy way although I have 0 idea if its actually running now or not.
